apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-rubber-stamp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubelet-rubber-stamp
  template:
    metadata:
      labels:
        name: kubelet-rubber-stamp
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: kubelet-rubber-stamp
      priorityClassName: system-cluster-critical
      containers:
        - name: kubelet-rubber-stamp
          image: {{ .Values.image | default (printf "quay.io/kontena/kubelet-rubber-stamp-amd64:%s" .Chart.AppVersion) }}
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubelet-rubber-stamp"
